width: 640
height: 480
framerate: 30
image_format: rgb
use_video_port: True
exposure_mode: fixedfps

published_topics:
  image: /rpi2/pi_camera/image

pi_camera_urdf:
  optical_frame: /pi_camera_optical_frame
